name: Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/CitySearchApp
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: CitySearch
        path: ${{env.DOTNET_ROOT}}/CitySearchApp

  deploy-arm:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run ARM Deploy
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./Azure/template.json
          parameters: ./Azure/parameters-production.json

  deploy:
    runs-on: ubuntu-latest
    needs: deploy-arm
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: CitySearch

      - name: Azure Authenticate
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Application
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'InterviewCitySearch'
          slot-name: 'production'
          package: .